#!/usr/bin/env bash
## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

## Update Interval
interval=0

## Cpu Info
cpu_info() {
    cpu_load=$(grep -o "^[^ ]*" /proc/loadavg)

    printf "^c#000000^ ^b#c10023^ CPU"
    printf "^c#919191^ ^b#303030^ $cpu_load"
}

## Memory
memory() {
    printf "^c#000000^ ^b#c10023^  Mem"
    printf "^c#919191^ ^b#303030^ $(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)"
}

## Wi-fi
wlan() {
    case "$(cat /sys/class/net/w*/operstate 2>/dev/null)" in
        up) printf "^c#000000^ ^b#c10023^  ^d^%s" "^c#919191^^b#303030^ Connected" ;;
        down) printf "^c#c6c6c6^ ^b#ffffff^ 睊 ^d^%s" "^c#a5a5a5^^b#c6c6c6^ Disconnected" ;;
    esac
}

## Time
clock() {
    printf "^c#000000^ ^b#c10023^ "
    printf "^c#919191^ ^b#303030^ $(date '+%b/%d/%Y, %a, %I:%M %p') "
}

## Main
while true; do
  [ "$interval" == 0 ] || [ $(("$interval" % 3600)) == 0 ] && updates=$(updates)
  interval=$((interval + 1))

  sleep 1 && xsetroot -name "$(cpu_info) $(memory) $(wlan) $(clock)"
done
